### ISSUE TITLE
Can I help ?

### ISSUE THREAD

**Issue by JeanTheFungle** [edqx/MouthwashGG#1]
hey @edqx i wante really help you in Polus.gg I love very much this mod I have many idea and many things it possible i can help please 

Here my discord account contact me plz = jeanamongus

**Comment by edqx** [comment]
The client and server are closed source for now. The launcher is available at https://github.com/edqx/MouthwashPublic, but you won't be able to help right now because it's not completely ready to play. Feel free to play the game and let me know of any issues you encounter by submitting a GitHub issue at https://github.com/edqx/MouthwashPublic/issues.

**Comment by JeanTheFungle** [comment]
> The client and server are closed source for now. The launcher is available at https://github.com/edqx/MouthwashPublic, but you won't be able to help right now because it's not completely ready to play. Feel free to play the game and let me know of any issues you encounter by submitting a GitHub issue at https://github.com/edqx/MouthwashPublic.git.

ok Thanks but i can bring to Among us 2023.7.12 and fix bug if you share with source code in discord private i will not post it in github or any ohter website and i swear. we can talk in discord if you wante 👍

**Comment by edqx** [comment]
I'm not taking any additional help right now, thanks for the offer.
